const assets = {
    images : {
        atm  : require("./landing_page/atm-card.png"),
        badge  : require("./landing_page/badge.png"),
        calender  : require("./landing_page/calender.png"),
        diagnostic  : require("./landing_page/diagnostic.png"),
        doctors  : require("./landing_page/doctors.png"),
        facebook  : require("./landing_page/facebook.png"),
        folder  : require("./landing_page/folder.png"),
        instagram  : require("./landing_page/instagram.png"),
        linkedin  : require("./landing_page/linkedin.png"),
        location  : require("./landing_page/location.png"),
        // search  : require("./landing_page/search.jpg"),
        search  : require("./landing_page/search.png"),
        twitter  : require("./landing_page/twitter.png"),
        user  : require("./landing_page/user.png"),
        video_call  : require("./landing_page/video_call.png"),

        stetoscope : require("./images/Stetoscope.png"),
        doctor1 : require("./images/doctor1.png"),
        doctor2 : require("./images/doctor2.png"),
        doctor3 : require("./images/doctor3.png"),
        familyOnBeach : require("./images/familyOnBeach.png"),
    },

    svgs : {
        Cardiology : require("./svgs/Cardiology.svg"),
        Dentist : require("./svgs/Dentist.svg"),
        Neurology : require("./svgs/Neurology.svg"),
        Ophthalmology : require("./svgs/Ophthalmology.svg"),
        Orthopedic : require("./svgs/Orthopedic.svg"),
        Urology : require("./svgs/Urology.svg"),
        arrow : require("./svgs/arrow.svg"),
        award : require("./svgs/award-icon.svg"),
        brain : require("./svgs/brain.svg"),
        calender : require("./svgs/calender.svg"),
        call : require("./svgs/call-icon.svg"),
        care : require("./svgs/care-icon.svg"),
        dna : require("./svgs/dna.svg"),
        doctorSearch : require("./svgs/doctorSearch.svg"),
        grid : require("./svgs/grid.svg"),
        kidney : require("./svgs/kidney.svg"),
        location : require("./svgs/location.svg"),
        logo : require("./svgs/logo.svg"),
        medical : require("./svgs/medical-equipment-icon.svg"),
        profile : require("./svgs/profile.svg"),
        schedule : require("./svgs/schedule.svg"),
        search : require("./svgs/search.svg"),
        solution : require("./svgs/solution.svg"),
    }
}
export default assets;